feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from feed import urls as feeds_urls # urls importando de feed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feeds_urls, namespace='feed'))
]

# Configuração para debug
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False) # campo text de tamanho 140 caracters, blank - fazio, null em branco
    image = ImageField()

    def __str__(self):
        return self.text # retorna o nome do text para que seja mostrado na pagina /admin

feed/forms.py
from django import forms

class PostForm(forms.Form):
    image = forms.FileField()
    text = forms.CharField(label="Description")

    

feed/views.py
from django.contrib import messages
from django.http import request
from django.views.generic import TemplateView, DetailView, FormView

# Importando o model Post de models.py
from .models import Post
from .forms import PostForm

class HomePageView(TemplateView):
    template_name = "home.html"

    # Passando uma variavel para view
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['my_thing'] = 'Olá Thiago, tudo bem com vc :P'
    #     return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id') # Post é o nome do model, order_by ordena por ordem decrescente
        return context

class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post

class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    success_url = "/"

    # Leva a mensagem para a pagina
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        new_object = Post.objects.create(
            text = form.cleaned_data['text'],
            image = form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, "Novo Post!") # Cria a mensagem
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}Image Share{% endblock %}</title>
</head>

<body>

    <!-- Init Navbar -->
    {% include "includes/navbar.html" %}
    <!-- End Navbar -->

    
    {% if messages %}
        {% for message in messages %}
            <div class="bg-{% if messages.tags %}{{ message.tags }}{% else %}success{% endif %} bg-gradient text-center text-white py-4">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <div class="container">
        {% block body %}{% endblock %}
    </div>
</body>
</html>

templates/detail.html
{% extends "base.html" %}


{% block title %}Detail View{% endblock %}

{% block body %}
    <div class="row text-center">
        <div class="col-sm-10 pt-5">
            <h1>{{ object.text }}</h1>    
            <img src="{{ object.image.url }}" class="img-fluid rounded"/>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}Feed{% endblock %}

{% block body %}
    <div class="row">
        {% for post in posts %}
            <div class="col-sm-6 col-md-3">

                <div class="card my-4">
                    {% thumbnail post.image "100x100" crop="center" as im %}
                    <img src="{{ post.image.url }}" class="card-img-top" alt="...">
                    {% endthumbnail %}
                    <div class="card-body">
                        <p class="card-text">{{ post.text }}</p>
                        <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View full image</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-sm-6 offset-3 text-center py-5 my-5">
                <h3>Welcome!</h3>
                <p>Add your first image?</p>
                <a href="{% url 'feed:post' %}" class="btn btn-lg btn-success">Upload image</a>
            </div>    
        {% endfor %}
    </div>
{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Image Share</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'feed:index'%}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feed:post' %}">Add new image</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/new_post.html
{% extends "base.html" %}


{% block title %}Upload a new image{% endblock %}

{% block body %}
    <form action="" method="post" enctype="multipart/form-data" class="col-sm-4 offset-4 pt-5">
        <h2>Upload an image</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button type="submit" class="btn btn-success">
                Submit form
            </button>
        </div>
    </form>
{% endblock %}